"""create generation_jobs and certificates

Revision ID: 018863196b52
Revises: 
Create Date: 2026-10-07 16:16:18.614644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018863196b52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('certificate_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'PROCESSING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED')", name=op.f('ck_generation_jobs_valid_status')),
    sa.CheckConstraint('success_count >= 0 AND failure_count >= 0', name=op.f('ck_generation_jobs_non_negative_counts')),
    sa.CheckConstraint('total_count > 0', name=op.f('ck_generation_jobs_positive_total')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_generation_jobs_idempotency_key'))
    )
    op.create_index('ix_generation_jobs_status', 'generation_jobs', ['status'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'SUCCESS' OR storage_key IS NOT NULL", name=op.f('ck_certificates_success_has_storage_key')),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')", name=op.f('ck_certificates_valid_status')),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], name=op.f('fk_certificates_job_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_index('ix_certificates_job_id_status', 'certificates', ['job_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certificates_job_id_status', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_generation_jobs_status', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
